export type {
  AssignRolesRequest,
  ChangeUserStatusRequest,
  CreateResourceRequest,
  CreateResourceActionRequest,
  CreateUserResponse,
  CreateRoleRequest,
  CreateUserRequest,
  ManagedRole,
  ManagedUser,
  PermissionItem,
  PermissionSummary,
  ResetPasswordResponse,
  ResourceItem,
  ResourceModuleCode,
  ResourceReference,
  ResourceStatus,
  UpdateResourceRequest,
  UpdateResourceActionRequest,
  UpdateRoleRequest,
  UpdateUserProfileRequest,
} from '@cove/shared';
